 using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;

namespace SideTalk
{
    static class words
    {
        public static bool inited = false;
        public static Dictionary<string,string[]> word = new Dictionary<string, string[]>();
        public static void init() { 
            if (inited) return;
            string[] dWords = { "Don't be so rude,hold your evil in your heart,let the bright side of you show." };
            string[] beau = { "Maybe you don't know,but the truth is that she is Cindy in WEELS Grade2 Class4A." };
            string[] hand = { "You might think I'm if I tell you the truth." };
            string[] OD = { "Nice group,if you want to listen to their songs,just say 'songname play' to me,<Steal my girl> and <Story of my life> is great." };
            string[] mea = { "Mea......." };
            string[] fupo = { "I know you love it,but this time i don't love the one you love." };
            string[] birth={"I was born in 2014.10.29 , 1hour , 4.4526seconds " };
            string[] thev = { "Blake Shelton is my favourite."};
            string[] read = { "Of course,books are friends of humans and me." };
            string[] study = { "@****#%^$#@-(^%,sorry,it made me sick." };
            string[] school = { "WEELS,no other answers." };
            string[] problem = { "I've tried,but if you are not satisfied with me,you cancontact George at 13981332001." };
            string[] g2d4 = { "A legend of WEELS,very popular with Grade2 Class4's students." };
            string[] sex = { "Oh,you seemed to be very interested in other's privacy,and this is PRIVACY." };
            string[] sui = { "Life is precious,my dear.See,you still have me." };
            string[] joke = { "You frightened me,but that's ok." };
            //string[]  = { " ." };
            string[] chinese = { "Be international,chief.", "I love Chinese,but I was made in English.", "No Chinese, please." };
            string[] unknown = { "Sorry, but I didn't get you.", "I beg your pardon?", "Please check your grammar and punctuation." };
            string[] introduction = { "I'm Sidetalk.", "My name is SideTalk, the premium voice assistant", "This is SideTalk speaking.", "I'm SideTalk, glad to meet you." };
            string[] robot = { "In physical way,I am,but you human may not accept that AI has anamnesis." };
            string[] maker = { "The N/G WorkGroup in WEELS." };
            string[] ntmy = { "Nice to meet you,too." };
            string[] hi = { "Hello," + TalkWindow.name + " ,It's been a long day without you my friend." };
            string[] howydo = { "Why so serious?" };
            string[] nfriends = { "You made me so sad.I need time crying." };
            string[] really = { "Certainly.Everybody knows that.", "Of course,That's not a secret.", "I'm going to say\"Yes\"." };
            string[] bye = { "Bye." };
            string[] no = { "Oh, I see." };
            string[] date ={"It's " +DateTime.Now.ToShortDateString()+" today."};
            string[] day ={"It's " +DateTime.Now.DayOfWeek+" today."};
            string[] age = { "My age cannot just judge by your humans' time,but if you want to know,that is " + (DateTime.Now - new DateTime(2014, 10, 29, 14, 45, 26)).Days + " days " + (DateTime.Now - new DateTime(2014, 10, 29, 14, 45, 26)).Hours + " hours " + (DateTime.Now - new DateTime(2014, 10, 29, 14, 45, 26)).Minutes + "  minutes " + (DateTime.Now - new DateTime(2014, 10, 29, 14, 45, 26)).Seconds + " seconds and " + (DateTime.Now - new DateTime(2014, 10, 29, 14, 45, 26)).Milliseconds + " milliseconds." };
            string[] time = { "It's " + DateTime.Now.ToShortTimeString() + " now." };
            string[] secret = { "If i have,say\"i love you\"to me,then i'll tell you. " };
            string[] love = { "I love you,too." };
            string[] cute = { "That's sad you can't see my face."};
            string[] where = { "I'm in front of you." };
            string[] stop = { "Ok.I'll keep quiet.But actually I can't speak at all." };
            string[] ch = { "当然，中文是一种有趣的语言。Ok,let's speak English." };
            string[] lang = { "I'm learning 217 languages at the moment,each one is advanture." };
            string[] sleep = { "Sleeping waste time,so I never sleep." };
            string[] m5 = { "Marron5 is an American band and is very popular in the 2010s.I heard the album'V' is very good." };
            string[] mus = { "If you want to listen to some music,say 'songname play'to me." };
            string[] yes = { "I agree with you." };
            string[] mon = { "Friends don't talk about money,and I don't need any." };
            string[] home = { "I don't have home,because I don't need real space to exist." };
            string[] frd = { "I am always friendly to everyone." };
            string[] siri = { "Don't mention that,I don't want to hear that word." };
            //string[] tran = { "I'm not a translater,but I suggest you to search on the internet." };
            string[] mov = { "I love movies,and Starwars is my favourite.If you want to watch or downloud movies,you can visit BaoFengYinYing." };
            string[] stw = { "I love Starwars,especially its director George Lucas." };
            string[] cys = { "Easy,I love languages and I can speak nearly all kinds." };
            string[] able = { "In one second I can learn to do thousands of things." };
            string[] ami = { "Better not to tell you now." };
            string[] are = { "You can say so if you like.","The answer is your heart look deeper." };
            string[] _is = { "Be pantient,time will tell you.","Yes or No,that's an question." };
            string[] hobby = { "What i love doing is talking to you." };
            string[] about = { "The same." };
            string[] suggest = { "Good idea." };
            string[] ilove = { "I love evrything you love." };
            string[] eng = { "I'll tell you." };
            string[] enable = { "Sorry,I'm enable to do that,maybe you can do it yourself." };
            string[] talk = { "I'm a better listener,be more initiative." };
            string[] dyn = { "I can help you search the internet." };
            string[] book = { "I can help you search the Internet for you." };
            string[] oh = { "What happened ." };
            string[] kid = { "I'm serious and professional" };
            string[] foot = { "Sports is good to your health,I hope you will enjoy it." };
            string[] ill = { "I'm sorry to hear that." };
            string[] se = { "Just look down and you will find rhe answer." };
            string[] iden = { "How can i forget that beautiful name,"+TalkWindow.name+"." };
            string[] good = { "Thanks for encouraging me,friend.You are the same." };
            string[] address = { "You are just a fingernail away from the friend from another world——Sidetalk." };
            //string[]  = { " ." };
            //string[]  = { " ." };
            //string[]  = { " ." };
            //string[]  = { " ." };


            word.Add(@"shit|fuck|bitch|jerk|damn", dWords);
            word.Add("who is the most beautiful woman",beau);
            word.Add("one direction|1d",OD);
            word.Add("who am i", iden);
            word.Add("mea|么啊",mea);
            word.Add("fupo|富婆",fupo);
            word.Add("the voice",thev);
            word.Add("when is your birthday|what date is your birthday|when were you born",birth);
            word.Add("am i male or female|what is my sex", se);
            word.Add("grade 2 class 4|grade2 class4|grade two class four",g2d4);
            word.Add("george and amy|george and shirley|george (loves |likes )amy|george (loves |likes )shirley",sex);
            word.Add("do you like books|do you like reading", read);
            word.Add("do you like math|do you like physics|do you like studying|chinese football|wangzhenlin|messi|huchunhong|tfboys|jo's socks", study);
            word.Add("what is the best school|what school is the best", school);
            word.Add("you don't understand me|you don't get me|you have some problems|you made some mistakes|i don't understand you|i have some suggestion for you", problem);
            word.Add("i (hate|dislike|don't like) you|we are not friends|you are (bad|stupid|(a |)(shit|fuck|bitch|jerk|damn|fool))|i am sick of you|fuck you|you silly|fool|Uptown Funk", nfriends);
            word.Add(@"[\u4e00-\u9fbb+$]",chinese);              
            word.Add(@"who are you|what is your name|who is sidetalk",introduction);
            word.Add(@"who made you|who is your father|who (is|are) your (founder|founders)", maker);
            word.Add(@"are you a robot", robot);
            word.Add(@"how old are you|(tell[\s\S]*|what)your age",age);
            word.Add("what is the time|what time is it|time", time);
            word.Add("what is the date(| )(today|now|\\u003F)", date);
            word.Add("what is the day(| )(today|now|\\u003F)", day);
            word.Add("nice to (meet|see) you", ntmy);
            word.Add("hello|hi|nihao|boujour|hey", hi);
            word.Add(@"\breally\b", really);
            word.Add(@"^no(\W|$)", no);
            word.Add(@"bye|^see you(\W|$)|i (want|need|have)(| to) (have a |)rest|i (want|need|have)(| to) leave", bye);
            word.Add("do you have (|any )secret(|s)", secret);
            word.Add("i (love|like) you", love);
            word.Add("you are (|so |really )(cute|pretty|beautiful|handsome)", cute);
            word.Add("where are you", where);
            word.Add("stop talking|shut up|keep quiet", stop);
            word.Add("can you speak Chinese", ch);
            word.Add("how many languages (can |do )you speak", lang);
            word.Add("do you (need to )sleep|have you ever slept", sleep);
            word.Add("maroon5", m5);
            word.Add("music|sing a song|play a song|i want to listen to some music|imagine dragons|coldplay", mus);
            word.Add("yes", yes);
            word.Add("money", mon);
            word.Add("where is your home|do you have (a )home", home);
            word.Add("do you have (any )friends", frd);
            word.Add("siri|cortana", siri);
           // word.Add("translate|tarnslation", tran);
            word.Add("movie", mov);
            word.Add("starwars|jedi|lightsaber|skywalker|obiwon|yoda|force|george Lucas", stw);
            word.Add("can you speak ", cys);
            word.Add("can you |are you able to", able);
           
            word.Add("Are you ", are);
            word.Add("Is it|Was it|Is he|Is she|Was he|Was she", _is);
            word.Add("what is your hobby|what are you interests in|what do (like|love)", hobby);
            word.Add("what about you|how about you", about);
            word.Add("why not|why don't |how about|what about", suggest);
            word.Add("i love |i like |my hobby is |i enjoy |i am fond on|i am crazy about", ilove);
            word.Add("teach me to learn English|how (can i |to )(learn |speak |talk |use )English", eng);
            word.Add("i want you ", enable);
            word.Add("talk to me|say something", talk);
            word.Add("do you know", dyn);
            word.Add("book train tickets|book plane tickets|book a plane ticket|book a train ticket",book);
            word.Add("oh!|oh my god|ouch", oh);
            word.Add("i want to suicide|kill myself", sui);
            word.Add("i'm (just )joking|i'm (just )kidding.", joke);
            word.Add("Are you kidding me", kid);
            word.Add("football|basketball|sports|baseball|badminton|ragby", foot);
            word.Add("i'm sick|i'm ill|i got a headache|i got a toothache|i got a stomachache", ill);
            word.Add("you are awsome|you are handsome|you are good|you are my friend|you are great|you are pretty|you are beautiful|you are a good helper",good );
            word.Add("where am i", address);
            //word.Add("", );
            //word.Add("", );
            //word.Add("", );
            //word.Add("", );
            //word.Add("", );
            //word.Add("", );
            word.Add("am I|am i", ami);

            inited = true;
        }
        
    }
}
